config:
  overlay-directories:
    - { source: "defconfig", target: "configs" } # copies all files in defconfig dir to the configs/ dir in the u-boot source tree
    - { source: "dt_upstream_allwinner", target: "dts/upstream/src/arm64/allwinner" } # copies all files in dt_upstream_allwinner dir to the dts/upstream/src/arm64/allwinner dir in the u-boot source tree
    - { source: "dt_uboot", target: "arch/arm/dts" } # copies all files in dt_uboot dir to the arch/arm/dts dir in the u-boot source tree
