# Allwinner A10 single core 1Gb SoC
INTRODUCED=2018
BOARD_NAME="Mele A1000"
BOARD_VENDOR="allwinner"
BOARDFAMILY="sun4i"
BOARD_MAINTAINER=""
HAS_VIDEO_OUTPUT="no"
BOOTCONFIG="Mele_A1000_defconfig"
KERNEL_TARGET="current,edge,legacy"
KERNEL_TEST_TARGET="current"
